#requires -Version 5.1
<#
Offline removal of a receipt-owned standalone installation. Uses the exact
verified retained installer bootstrap; never changes execution policy.
Generated by scripts/render-windows-uninstaller.py; shared checks come from install.ps1.
#>
[CmdletBinding()]
param([string]$InstallDirectory)

function Get-LocronSid {
    [Security.Principal.WindowsIdentity]::GetCurrent().User.Value
}

function ConvertTo-LocronPath([string]$Path) {
    if ($Path -notmatch '^[A-Za-z]:[\\/]' -or $Path -match '[\x00-\x1f]' -or $Path.Substring(2).Contains(':')) {
        throw 'locron requires an absolute local drive path without alternate streams'
    }
    $full = [IO.Path]::GetFullPath($Path)
    foreach ($part in $full.Substring(3).Split('\')) {
        if ($part -match '[. ]$' -or $part -match '^(?i:CON|PRN|AUX|NUL|COM[1-9\u00b9\u00b2\u00b3]|LPT[1-9\u00b9\u00b2\u00b3])(?:\..*)?$') {
            throw 'locron refuses ambiguous Windows path components'
        }
    }
    if ($full.Length -eq 3) { $full } else { $full.TrimEnd('\') }
}

function Assert-LocronDescriptor($Security, [bool]$Private, [bool]$Directory) {
    $sid = Get-LocronSid
    $owner = $Security.GetOwner([Security.Principal.SecurityIdentifier]).Value
    $trusted = @($sid, 'S-1-5-18', 'S-1-5-32-544',
        'S-1-5-80-956008885-3418522649-1831038044-1853292631-2271478464')
    if (($Private -and $owner -ne $sid) -or (-not $Private -and $owner -notin $trusted)) {
        throw 'locron refuses foreign-owned filesystem objects'
    }
    $user = $false
    $system = $false
    foreach ($rule in $Security.GetAccessRules($true, $true, [Security.Principal.SecurityIdentifier])) {
        if (-not $Private -and ($rule.PropagationFlags -band [Security.AccessControl.PropagationFlags]::InheritOnly)) { continue }
        if ($rule.AccessControlType -ne [Security.AccessControl.AccessControlType]::Allow) {
            if ($Private) { throw 'locron private files require a current-user/SYSTEM allow DACL' }
            continue
        }
        $principal = $rule.IdentityReference.Value
        $mask = [long]$rule.FileSystemRights
        if ($Private) {
            if ($principal -notin @($sid, 'S-1-5-18') -or ($mask -band 0x1f01ff) -ne 0x1f01ff -or
                ($rule.PropagationFlags -band [Security.AccessControl.PropagationFlags]::InheritOnly)) {
                throw 'locron private files require full control only for the current user and SYSTEM'
            }
            if ($Directory -and ($rule.InheritanceFlags -band 3) -ne 3) {
                throw 'locron private directory permissions must inherit onto files and directories'
            }
            $user = $user -or $principal -eq $sid
            $system = $system -or $principal -eq 'S-1-5-18'
        } elseif ($principal -notin $trusted -and ($mask -band 0x500d0152)) {
            # Active writes, deletion or permission changes could mutate an ancestor.
            # Directory CreateDirectories alone does not authorize replacing it.
            throw 'locron refuses an ancestry that another account can replace'
        }
    }
    if ($Private -and (-not $user -or -not $system -or ($Directory -and -not $Security.AreAccessRulesProtected))) {
        throw 'locron requires a protected private directory with current-user and SYSTEM access'
    }
}

function Assert-LocronDirectory([string]$Path, [bool]$Private = $false) {
    $full = ConvertTo-LocronPath $Path
    $directory = [IO.DirectoryInfo]::new($full)
    if (-not $directory.Exists -or ($directory.Attributes -band [IO.FileAttributes]::ReparsePoint)) {
        throw 'locron refuses missing directories and reparse points'
    }
    Assert-LocronDescriptor ($directory.GetAccessControl()) $Private $true
    if ($null -ne $directory.Parent) { $null = Assert-LocronDirectory $directory.Parent.FullName }
    $full
}

function Read-LocronPrivateFile([string]$Path) {
    $full = ConvertTo-LocronPath $Path
    $null = Assert-LocronDirectory ([IO.Path]::GetDirectoryName($full)) $true
    if (([IO.File]::GetAttributes($full) -band [IO.FileAttributes]::ReparsePoint)) { throw 'locron refuses reparse files' }
    $stream = [IO.File]::Open($full, [IO.FileMode]::Open, [IO.FileAccess]::Read, [IO.FileShare]::Read)
    try {
        Assert-LocronDescriptor ($stream.GetAccessControl()) $true $false
        if ($stream.Length -gt 67108864) { throw 'locron file exceeds the staging limit' }
        $buffer = [IO.MemoryStream]::new()
        try { $stream.CopyTo($buffer); return ,$buffer.ToArray() } finally { $buffer.Dispose() }
    } finally { $stream.Dispose() }
}

function Get-LocronSha256([byte[]]$Bytes) {
    $hash = [Security.Cryptography.SHA256]::Create()
    try { ([BitConverter]::ToString($hash.ComputeHash($Bytes))).Replace('-', '').ToLowerInvariant() }
    finally { $hash.Dispose() }
}

function ConvertFrom-LocronJson([byte[]]$Bytes) {
    if ($Bytes.Length -gt 131072) { throw 'locron metadata exceeds its size limit' }
    $json = [Text.UTF8Encoding]::new($false, $true).GetString($Bytes)
    # ConvertFrom-Json silently collapses duplicate keys. Reject duplicates in
    # each object first, including escaped/case-variant spellings on PowerShell.
    $objects = [Collections.Generic.Stack[Collections.Generic.HashSet[string]]]::new()
    for ($offset = 0; $offset -lt $json.Length; $offset++) {
        $character = $json[$offset]
        if ($character -eq '{') {
            if ($objects.Count -ge 32) { throw 'locron JSON nesting exceeds its limit' }
            $objects.Push([Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase))
        } elseif ($character -eq '}') {
            if ($objects.Count -eq 0) { throw 'invalid locron JSON object' }
            $null = $objects.Pop()
        } elseif ($character -eq '/' -or $character -eq "'") {
            throw 'locron metadata requires standard JSON without comments or single quotes'
        } elseif ($character -cmatch '[A-Za-z_$]') {
            $tokenEnd = $offset + 1
            while ($tokenEnd -lt $json.Length -and $json[$tokenEnd] -cmatch '[A-Za-z0-9_$]') { $tokenEnd++ }
            $following = $tokenEnd
            while ($following -lt $json.Length -and [char]::IsWhiteSpace($json[$following])) { $following++ }
            if ($following -lt $json.Length -and $json[$following] -eq ':') { throw 'locron JSON fields must be quoted' }
            if ($json.Substring($offset, $tokenEnd - $offset) -cnotin @('true', 'false', 'null', 'e', 'E')) { throw 'invalid locron JSON token' }
            $offset = $tokenEnd - 1
        } elseif ($character -eq '"') {
            $key = [Text.StringBuilder]::new()
            $closed = $false
            while (++$offset -lt $json.Length) {
                $character = $json[$offset]
                if ($character -eq '"') { $closed = $true; break }
                if ([int]$character -lt 32) { throw 'invalid locron JSON string' }
                if ($character -eq '\') {
                    if (++$offset -ge $json.Length) { throw 'truncated locron JSON escape' }
                    $escape = $json[$offset]
                    switch -CaseSensitive ($escape) {
                        '"' { $null = $key.Append('"') }
                        '\' { $null = $key.Append('\') }
                        '/' { $null = $key.Append('/') }
                        'b' { $null = $key.Append([char]8) }
                        'f' { $null = $key.Append([char]12) }
                        'n' { $null = $key.Append([char]10) }
                        'r' { $null = $key.Append([char]13) }
                        't' { $null = $key.Append([char]9) }
                        'u' {
                            if ($offset + 4 -ge $json.Length -or $json.Substring($offset + 1, 4) -cnotmatch '^[a-fA-F0-9]{4}$') {
                                throw 'invalid locron JSON Unicode escape'
                            }
                            $null = $key.Append([char][Convert]::ToInt32($json.Substring($offset + 1, 4), 16))
                            $offset += 4
                        }
                        default { throw 'invalid locron JSON escape' }
                    }
                } else { $null = $key.Append($character) }
            }
            if (-not $closed) { throw 'unterminated locron JSON string' }
            $next = $offset + 1
            while ($next -lt $json.Length -and [char]::IsWhiteSpace($json[$next])) { $next++ }
            if ($next -lt $json.Length -and $json[$next] -eq ':') {
                if ($objects.Count -eq 0 -or -not $objects.Peek().Add($key.ToString())) { throw 'duplicate locron JSON field' }
            }
        }
    }
    if ($objects.Count -ne 0) { throw 'unterminated locron JSON object' }
    ConvertFrom-Json -InputObject $json
}

function Assert-LocronFields($Value, [string[]]$Fields) {
    if ($Value -isnot [Management.Automation.PSCustomObject]) { throw 'locron metadata must be a JSON object' }
    $actual = @($Value.PSObject.Properties.Name)
    if ($actual.Count -ne $Fields.Count) { throw 'locron metadata has missing or unknown fields' }
    foreach ($field in $Fields) {
        if (@($actual | Where-Object { $_ -ceq $field }).Count -ne 1) { throw 'locron metadata has missing or unknown fields' }
    }
}

function Assert-LocronUserPath($Record, [string]$Directory) {
    Assert-LocronFields $Record @('before', 'after', 'before_kind', 'after_kind')
    $directory = ConvertTo-LocronPath $Directory
    if ($Record.after -isnot [string] -or $Record.after_kind -isnot [string] -or
        $Record.after_kind -cnotin @('String', 'ExpandString') -or
        (($null -eq $Record.before) -ne ($null -eq $Record.before_kind)) -or
        ($null -ne $Record.before -and ($Record.before -isnot [string] -or
            $Record.before_kind -isnot [string] -or $Record.before_kind -cnotin @('String', 'ExpandString'))) -or
        $directory.Contains(';') -or $Record.after.IndexOf([char]0) -ge 0 -or
        ($null -ne $Record.before -and $Record.before.IndexOf([char]0) -ge 0)) { throw 'invalid receipt PATH record' }
    $kind = if ($null -eq $Record.before_kind) { 'String' } else { $Record.before_kind }
    if ($Record.after_kind -cne $kind -or ($kind -ceq 'ExpandString' -and $directory.Contains('%'))) {
        throw 'PATH insertion changed kind or would expand the literal directory'
    }
    $expected = $directory
    if ($null -ne $Record.before -and $Record.before.Length -gt 0) {
        $separator = if ($Record.before.EndsWith(';')) { '' } else { ';' }
        $expected = $Record.before + $separator + $directory
    }
    if ($Record.after -cne $expected) { throw 'PATH record is not one literal installer insertion' }
}

function Read-LocronReceipt([string]$Directory) {
    $full = Assert-LocronDirectory $Directory $true
    $receipt = ConvertFrom-LocronJson (Read-LocronPrivateFile ([IO.Path]::Combine($full, '.locron-install-receipt-v1')))
    Assert-LocronFields $receipt @('schema', 'sid', 'channel', 'directory', 'executable', 'target', 'version',
        'archive_url', 'archive_sha256', 'binary_sha256', 'files', 'user_path')
    if ($receipt.schema -cne 'locron.install/windows-v1' -or $receipt.sid -cne (Get-LocronSid) -or
        $receipt.channel -cne 'standalone' -or $receipt.target -cne (Get-LocronTarget) -or
        $receipt.version -cnotmatch '^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$' -or
        [Version]$receipt.version -lt [Version]'0.10.0' -or
        $receipt.directory -isnot [string] -or $receipt.executable -isnot [string] -or
        -not [StringComparer]::OrdinalIgnoreCase.Equals((ConvertTo-LocronPath $receipt.directory), $full) -or
        -not [StringComparer]::OrdinalIgnoreCase.Equals((ConvertTo-LocronPath $receipt.executable), ([IO.Path]::Combine($full, 'locron.exe')))) {
        throw 'receipt does not authorize this user, channel, native version or exact installation'
    }
    $asset = "locron-v$($receipt.version)-$($receipt.target).zip"
    if ($receipt.archive_url -cne "https://github.com/WhiteKiwi/locron/releases/download/v$($receipt.version)/$asset" -or
        $receipt.archive_sha256 -isnot [string] -or $receipt.archive_sha256 -cnotmatch '^[a-f0-9]{64}$' -or
        $receipt.binary_sha256 -isnot [string] -or $receipt.binary_sha256 -cnotmatch '^[a-f0-9]{64}$') { throw 'invalid canonical receipt digests' }
    $names = @('locron.exe', 'README.md', 'LICENSE-MIT', 'LICENSE-APACHE', 'uninstall.ps1', '.locron-installer.ps1')
    Assert-LocronFields $receipt.files $names
    foreach ($name in $names) {
        if ($receipt.files.$name -isnot [string] -or $receipt.files.$name -cnotmatch '^[a-f0-9]{64}$') { throw 'invalid receipt file digest' }
    }
    if ($receipt.files.'locron.exe' -cne $receipt.binary_sha256) { throw 'receipt executable digests disagree' }
    if ($null -ne $receipt.user_path) {
        Assert-LocronUserPath $receipt.user_path $receipt.directory
    }
    $receipt
}

function Get-LocronTarget {
    switch ([Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString()) {
        'X64' { 'x86_64-pc-windows-msvc' }
        'Arm64' { 'aarch64-pc-windows-msvc' }
        default { throw 'locron publishes only native Windows x64 and ARM64' }
    }
}

function Invoke-LocronRemovalBootstrap {
    $selected = $InstallDirectory
    if (-not $selected) {
        $selected = if ([IO.File]::Exists([IO.Path]::Combine($PSScriptRoot, '.locron-install-receipt-v1'))) {
            $PSScriptRoot
        } else { [IO.Path]::Combine($env:LOCALAPPDATA, 'Programs', 'locron') }
    }
    $selected = ConvertTo-LocronPath $selected
    $receipt = Read-LocronReceipt $selected
    $bootstrapPath = [IO.Path]::Combine($selected, '.locron-installer.ps1')
    $bootstrap = Read-LocronPrivateFile $bootstrapPath
    if ((Get-LocronSha256 $bootstrap) -cne $receipt.files.'.locron-installer.ps1') {
        throw 'retained installer bootstrap changed; removal is refused'
    }
    # Keep the verified script immutable while its functions are loaded. Release
    # this source handle before the helper removes that owned payload; its loaded
    # functions are already in memory, and the helper repeats all live checks.
    $guard = [IO.File]::Open($bootstrapPath, [IO.FileMode]::Open, [IO.FileAccess]::Read, [IO.FileShare]::Read)
    try {
        Assert-LocronDescriptor ($guard.GetAccessControl()) $true $false
        if ($guard.Length -gt 67108864) { throw 'retained bootstrap exceeds its size limit' }
        $memory = [IO.MemoryStream]::new()
        try {
            $guard.CopyTo($memory)
            if ((Get-LocronSha256 $memory.ToArray()) -cne $receipt.files.'.locron-installer.ps1') {
                throw 'retained bootstrap changed before loading; removal is refused'
            }
        } finally { $memory.Dispose() }
        . $bootstrapPath -InstallDirectory $selected
    } finally { $guard.Dispose() }
    Invoke-LocronUninstall $selected
}

if ($MyInvocation.InvocationName -ne '.') {
    $ErrorActionPreference = 'Stop'
    $ProgressPreference = 'SilentlyContinue'
    Invoke-LocronRemovalBootstrap
}
