//! Access-token file management.
//!
//! The dashboard access token is 32 random bytes from the OS RNG, hex-encoded to 64 characters,
//! stored owner-only (0600) at a fixed name under the state directory. It is generated on first
//! use, reused afterwards, regenerated by `enable --reset`, and removed by `disable`. The server
//! reads it at startup; a running server is unaffected by a later file change, which is why
//! `enable --reset` restarts the service. The token never appears in a URL, in logs, or in
//! responses. Cooperating token operations serialize through a permanent private lock file;
//! disabling the dashboard removes the secret, not that empty synchronization object.

use std::fs;
use std::io::{self, ErrorKind, Read, Write};
use std::path::PathBuf;
use std::time::{Duration, Instant};

use locron_core::filesystem::{DirectoryGuard, GuardedFile, open_private_or_create};
use locron_store::StatePaths;

/// The fixed token file name under the state directory.
pub const TOKEN_FILE_NAME: &str = "dashboard.token";
const TOKEN_LOCK_FILE_NAME: &str = "dashboard.token.lock";
const TOKEN_FILE_LIMIT: u64 = 4096;
const TOKEN_LOCK_TIMEOUT: Duration = Duration::from_secs(5);

/// Returns the token file path under the state directory.
#[must_use]
pub fn token_path(paths: &StatePaths) -> PathBuf {
    paths.root.join(TOKEN_FILE_NAME)
}

/// Generates 32 random bytes and hex-encodes them to a 64-character string.
///
/// Used for the access token and for per-session CSRF values.
///
/// # Panics
///
/// Panics if the OS random number generator fails.
#[must_use]
pub fn random_hex_32() -> String {
    let mut bytes = [0_u8; 32];
    getrandom::fill(&mut bytes).expect("OS random number generator must be available");
    let mut hex = String::with_capacity(64);
    for byte in bytes {
        use std::fmt::Write;
        let _ = write!(hex, "{byte:02x}");
    }
    hex
}

/// Reads the token file, generating and persisting a fresh token when the file is missing.
///
/// The state root is created (refusing a symlink at the root, mirroring the store's
/// `ensure_private_directory` posture) and the file is written atomically with 0600 permissions.
/// First-use detection and creation share the same cross-process token lock.
pub fn ensure(paths: &StatePaths) -> io::Result<String> {
    let _lock = lock_token(paths, true)?;
    let path = token_path(paths);
    let read = || -> io::Result<String> {
        let mut file =
            locron_core::filesystem::open_private(&path, fs::OpenOptions::new().read(true))?;
        let mut contents = String::new();
        let bytes = (&mut *file)
            .take(TOKEN_FILE_LIMIT + 1)
            .read_to_string(&mut contents)?;
        if bytes as u64 > TOKEN_FILE_LIMIT {
            return Err(io::Error::new(
                ErrorKind::InvalidData,
                "dashboard token file exceeds its 4096-byte limit",
            ));
        }
        Ok(contents)
    };
    match read() {
        Ok(contents) => {
            let token = contents.trim();
            if valid_token(token) {
                Ok(token.to_owned())
            } else {
                Err(io::Error::new(
                    ErrorKind::InvalidData,
                    format!(
                        "{} does not contain a 64-character hex access token",
                        path.display()
                    ),
                ))
            }
        }
        Err(error) if error.kind() == ErrorKind::NotFound => {
            let token = random_hex_32();
            write_atomic_0600(&path, &token)?;
            Ok(token)
        }
        Err(error) => Err(error),
    }
}

/// Replaces the stored token with a fresh random one (`enable --reset` semantics).
pub fn regenerate(paths: &StatePaths) -> io::Result<String> {
    let _lock = lock_token(paths, true)?;
    let token = random_hex_32();
    write_atomic_0600(&token_path(paths), &token)?;
    Ok(token)
}

/// Removes the token file (`disable` semantics); a missing file is not an error.
/// The permanent, empty lock file remains so concurrent callers use the same lock identity.
pub fn remove(paths: &StatePaths) -> io::Result<()> {
    // Do not create a state directory merely to remove an absent token.
    match fs::symlink_metadata(&paths.root) {
        Err(error) if error.kind() == ErrorKind::NotFound => return Ok(()),
        Err(error) => return Err(error),
        Ok(_) => {}
    }
    let _lock = lock_token(paths, false)?;
    match locron_core::filesystem::remove_private_file(&token_path(paths)) {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == ErrorKind::NotFound => Ok(()),
        Err(error) => Err(error),
    }
}

/// Retains the actual lock handle and its parent guards throughout a token operation.
/// Only lock contention retries; synchronous filesystem calls themselves are not cancellable.
fn lock_token(paths: &StatePaths, create_root: bool) -> io::Result<GuardedFile> {
    let deadline = Instant::now() + TOKEN_LOCK_TIMEOUT;
    let root = if create_root {
        DirectoryGuard::private(&paths.root)?
    } else {
        DirectoryGuard::existing_private(&paths.root)?
    };
    let file = open_private_or_create(&root.normalized_path().join(TOKEN_LOCK_FILE_NAME))?;
    loop {
        if Instant::now() >= deadline {
            return Err(token_lock_timeout());
        }
        match file.try_lock() {
            Ok(()) => {
                if Instant::now() >= deadline {
                    return Err(token_lock_timeout());
                }
                // No duplicate handle escapes. Dropping this file releases the lock.
                return Ok(file);
            }
            Err(fs::TryLockError::WouldBlock) => {
                let remaining = deadline.saturating_duration_since(Instant::now());
                std::thread::sleep(remaining.min(Duration::from_millis(10)));
            }
            Err(fs::TryLockError::Error(error)) => return Err(error),
        }
    }
}

fn token_lock_timeout() -> io::Error {
    io::Error::new(
        ErrorKind::TimedOut,
        "dashboard token is busy; retry after the current token operation finishes",
    )
}

fn valid_token(token: &str) -> bool {
    token.len() == 64 && token.bytes().all(|byte| byte.is_ascii_hexdigit())
}

fn write_atomic_0600(path: &std::path::Path, contents: &str) -> io::Result<()> {
    let root = path.parent().expect("token path always has a parent");
    let _guard = locron_core::filesystem::DirectoryGuard::private(root)?;
    let temporary = root.join(format!(
        "{}.{}.tmp",
        path.file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("token"),
        random_hex_32()
    ));
    // A failed exclusive create does not authorize removing an existing file.
    let mut file = locron_core::filesystem::create_private_new(&temporary)?;
    let written = file
        .write_all(contents.as_bytes())
        .and_then(|()| file.sync_all());
    // Release the file before cleanup/rename, including on Windows.
    drop(file);
    if let Err(error) = written {
        let _ = locron_core::filesystem::remove_private_file(&temporary);
        return Err(error);
    }
    if let Err(error) = locron_core::filesystem::rename_private(&temporary, path) {
        let _ = locron_core::filesystem::remove_private_file(&temporary);
        return Err(error);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_paths() -> (tempfile::TempDir, StatePaths) {
        let dir = tempfile::tempdir().expect("tempdir");
        let paths = StatePaths::new(dir.path().join("private"));
        paths.ensure().expect("private test root");
        (dir, paths)
    }

    #[test]
    fn ensure_generates_then_reuses() {
        let (_dir, paths) = temp_paths();
        let first = ensure(&paths).expect("generate");
        assert!(valid_token(&first));
        let second = ensure(&paths).expect("reuse");
        assert_eq!(first, second, "an existing token must be reused");
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let metadata = fs::metadata(token_path(&paths)).expect("token file");
            assert_eq!(metadata.permissions().mode() & 0o777, 0o600);
        }
        assert!(locron_core::filesystem::is_private(&token_path(&paths), false).unwrap());
        assert_eq!(fs::read_to_string(token_path(&paths)).unwrap(), first);
    }

    #[test]
    fn regenerate_replaces_and_remove_deletes() {
        let (_dir, paths) = temp_paths();
        let first = ensure(&paths).expect("generate");
        let second = regenerate(&paths).expect("regenerate");
        assert_ne!(first, second);
        remove(&paths).expect("remove");
        assert!(fs::metadata(token_path(&paths)).is_err());
        remove(&paths).expect("second remove is a no-op");
    }

    #[test]
    fn corrupt_token_file_is_rejected() {
        let (_dir, paths) = temp_paths();
        locron_core::filesystem::create_private_new(&token_path(&paths))
            .expect("private token file")
            .write_all(b"not-a-token")
            .expect("write");
        assert_eq!(ensure(&paths).unwrap_err().kind(), ErrorKind::InvalidData);
    }
}
