//! Access-token file management.
//!
//! The dashboard access token is 32 random bytes from the OS RNG, hex-encoded to 64 characters,
//! stored owner-only (0600) at a fixed name under the state directory. It is generated on first
//! use, reused afterwards, regenerated by `enable --reset`, and removed by `disable`. The server
//! reads it at startup; a running server is unaffected by a later file change, which is why
//! `enable --reset` restarts the service. The token never appears in a URL, in logs, or in
//! responses. Cooperating token operations serialize through a permanent private lock file;
//! disabling the dashboard removes the secret, not that empty synchronization object.

use std::fs;
use std::io::{self, ErrorKind, Read, Write};
use std::path::PathBuf;
use std::time::{Duration, Instant};

#[cfg(not(windows))]
use locron_core::filesystem::open_private_or_create;
use locron_core::filesystem::{DirectoryGuard, GuardedFile};
use locron_store::StatePaths;

#[cfg(test)]
mod qualification;
#[cfg(test)]
mod test_support;

/// The fixed token file name under the state directory.
pub const TOKEN_FILE_NAME: &str = "dashboard.token";
const TOKEN_LOCK_FILE_NAME: &str = "dashboard.token.lock";
const TOKEN_FILE_LIMIT: u64 = 4096;
const TOKEN_LOCK_TIMEOUT: Duration = Duration::from_secs(5);

/// Returns the token file path under the state directory.
#[must_use]
pub fn token_path(paths: &StatePaths) -> PathBuf {
    paths.root.join(TOKEN_FILE_NAME)
}

/// Generates 32 random bytes and hex-encodes them to a 64-character string.
///
/// Used for the access token and for per-session CSRF values.
///
/// # Panics
///
/// Panics if the OS random number generator fails.
#[must_use]
pub fn random_hex_32() -> String {
    let mut bytes = [0_u8; 32];
    getrandom::fill(&mut bytes).expect("OS random number generator must be available");
    let mut hex = String::with_capacity(64);
    for byte in bytes {
        use std::fmt::Write;
        let _ = write!(hex, "{byte:02x}");
    }
    hex
}

/// Reads the token file, generating and persisting a fresh token when the file is missing.
///
/// The state root is created (refusing a symlink at the root, mirroring the store's
/// `ensure_private_directory` posture) and the file is written atomically with 0600 permissions.
/// First-use detection and creation share the same cross-process token lock.
pub fn ensure(paths: &StatePaths) -> io::Result<String> {
    let _lock = lock_token(paths, true)?;
    #[cfg(test)]
    test_support::observe(&paths.root, test_support::Event::TokenIo);
    let path = token_path(paths);
    let read = || -> io::Result<String> {
        let mut file =
            locron_core::filesystem::open_private(&path, fs::OpenOptions::new().read(true))?;
        let mut contents = String::new();
        let bytes = (&mut *file)
            .take(TOKEN_FILE_LIMIT + 1)
            .read_to_string(&mut contents)?;
        if bytes as u64 > TOKEN_FILE_LIMIT {
            return Err(io::Error::new(
                ErrorKind::InvalidData,
                "dashboard token file exceeds its 4096-byte limit",
            ));
        }
        Ok(contents)
    };
    match read() {
        Ok(contents) => {
            let token = contents.trim();
            if valid_token(token) {
                Ok(token.to_owned())
            } else {
                Err(io::Error::new(
                    ErrorKind::InvalidData,
                    format!(
                        "{} does not contain a 64-character hex access token",
                        path.display()
                    ),
                ))
            }
        }
        Err(error) if error.kind() == ErrorKind::NotFound => {
            #[cfg(test)]
            test_support::observe(&paths.root, test_support::Event::Decision);
            let token = random_hex_32();
            write_atomic_0600(&path, &token)?;
            Ok(token)
        }
        Err(error) => Err(error),
    }
}

/// Replaces the stored token with a fresh random one (`enable --reset` semantics).
pub fn regenerate(paths: &StatePaths) -> io::Result<String> {
    let _lock = lock_token(paths, true)?;
    #[cfg(test)]
    test_support::observe(&paths.root, test_support::Event::TokenIo);
    let token = random_hex_32();
    write_atomic_0600(&token_path(paths), &token)?;
    Ok(token)
}

/// Removes the token file (`disable` semantics); a missing file is not an error.
/// The permanent, empty lock file remains so concurrent callers use the same lock identity.
pub fn remove(paths: &StatePaths) -> io::Result<()> {
    // Do not create a state directory merely to remove an absent token.
    match fs::symlink_metadata(&paths.root) {
        Err(error) if error.kind() == ErrorKind::NotFound => return Ok(()),
        Err(error) => return Err(error),
        Ok(_) => {}
    }
    let _lock = lock_token(paths, false)?;
    #[cfg(test)]
    test_support::observe(&paths.root, test_support::Event::TokenIo);
    match locron_core::filesystem::remove_private_file(&token_path(paths)) {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == ErrorKind::NotFound => Ok(()),
        Err(error) => Err(error),
    }
}

/// Retains the actual lock handle and its parent guards throughout a token operation.
/// Only lock contention retries; synchronous filesystem calls themselves are not cancellable.
fn lock_token(paths: &StatePaths, create_root: bool) -> io::Result<GuardedFile> {
    let deadline = Instant::now() + TOKEN_LOCK_TIMEOUT;
    #[cfg(test)]
    test_support::begin(&paths.root, deadline);
    let root = if create_root {
        DirectoryGuard::private(&paths.root)?
    } else {
        DirectoryGuard::existing_private(&paths.root)?
    };
    #[cfg(not(windows))]
    let file = open_private_or_create(&root.normalized_path().join(TOKEN_LOCK_FILE_NAME))?;
    #[cfg(windows)]
    let file = open_windows_lock(&root, deadline)?;
    loop {
        if Instant::now() >= deadline {
            return Err(token_lock_timeout());
        }
        #[cfg(not(test))]
        let acquired = file.try_lock();
        #[cfg(test)]
        let acquired = test_support::try_lock(&paths.root, &file, deadline);
        match acquired {
            Ok(()) => {
                if Instant::now() >= deadline {
                    return Err(token_lock_timeout());
                }
                // No duplicate handle escapes. Dropping this file releases the lock.
                #[cfg(test)]
                test_support::observe(&paths.root, test_support::Event::Acquired);
                return Ok(file);
            }
            Err(fs::TryLockError::WouldBlock) => {
                #[cfg(test)]
                test_support::observe(&paths.root, test_support::Event::Busy);
                let remaining = deadline.saturating_duration_since(Instant::now());
                #[cfg(test)]
                test_support::observe(&paths.root, test_support::Event::Sleep);
                std::thread::sleep(remaining.min(Duration::from_millis(10)));
            }
            Err(fs::TryLockError::Error(error)) => return Err(error),
        }
    }
}

#[cfg(windows)]
fn lock_remaining(deadline: Instant) -> io::Result<()> {
    if Instant::now() >= deadline {
        Err(token_lock_timeout())
    } else {
        Ok(())
    }
}

// These two owners make the constructor/closed-unpublished boundary explicit.
// Neither an unsuccessful create nor an unknown native result authorizes adoption.
#[cfg(windows)]
struct CreatedOpenLock {
    file: GuardedFile,
    path: PathBuf,
}

#[cfg(windows)]
struct ClosedUnpublishedLock(tempfile::TempPath);

#[cfg(windows)]
impl CreatedOpenLock {
    fn close(self) -> io::Result<ClosedUnpublishedLock> {
        drop(self.file);
        let mut path = tempfile::TempPath::try_from_path(self.path)?;
        path.disable_cleanup(true);
        Ok(ClosedUnpublishedLock(path))
    }
}

#[cfg(windows)]
fn open_windows_lock(root: &DirectoryGuard, deadline: Instant) -> io::Result<GuardedFile> {
    let root_path = root.normalized_path();
    let final_path = root_path.join(TOKEN_LOCK_FILE_NAME);
    lock_remaining(deadline)?;
    match locron_core::filesystem::open_private(
        &final_path,
        fs::OpenOptions::new().read(true).write(true),
    ) {
        Ok(file) => {
            lock_remaining(deadline)?;
            return Ok(file);
        }
        Err(error) if error.kind() == ErrorKind::NotFound => {}
        Err(error) => return Err(error),
    }
    lock_remaining(deadline)?;
    let candidate_id = uuid::Uuid::now_v7();
    #[cfg(test)]
    let candidate_id = test_support::candidate_id(root_path).unwrap_or(candidate_id);
    let candidate_path = root_path.join(format!("{TOKEN_LOCK_FILE_NAME}.{candidate_id}.pending"));
    #[cfg(not(test))]
    let file = locron_core::filesystem::create_private_new(&candidate_path)?;
    #[cfg(test)]
    let file = test_support::create_candidate(root_path, &candidate_path, deadline)?;
    let created = CreatedOpenLock {
        file,
        path: candidate_path.clone(),
    };
    #[cfg(test)]
    test_support::observe(root_path, test_support::Event::CreatedOpen);
    // Close the owned leaf even if the synchronous constructor returned late.
    let ClosedUnpublishedLock(candidate) = created.close()?;
    #[cfg(test)]
    test_support::observe(root_path, test_support::Event::ClosedUnpublished);
    if let Err(error) = lock_remaining(deadline) {
        #[cfg(test)]
        test_support::observe(root_path, test_support::Event::Expired);
        return Err(error);
    }
    #[cfg(test)]
    test_support::before_publish(root_path, deadline);
    if let Err(error) = lock_remaining(deadline) {
        #[cfg(test)]
        test_support::observe(root_path, test_support::Event::Expired);
        return Err(error);
    }
    #[cfg(not(test))]
    let published = candidate.persist_noclobber(&final_path);
    #[cfg(test)]
    let published = test_support::publish(root_path, candidate, &final_path, deadline);
    match published {
        Ok(()) => {
            // PublishedFinal is permanent, including a late successful native return.
            #[cfg(test)]
            test_support::observe(root_path, test_support::Event::PublishedFinal);
            lock_remaining(deadline)?;
        }
        Err(mut refusal) => {
            let same_candidate = refusal.path.as_os_str() == candidate_path.as_os_str();
            assert!(
                same_candidate,
                "lock publication changed the owned candidate"
            );
            refusal.path.disable_cleanup(true);
            let collision = refusal.error.kind() == ErrorKind::AlreadyExists;
            #[cfg(test)]
            test_support::observe(
                root_path,
                if collision {
                    test_support::Event::Collision
                } else {
                    test_support::Event::PublishFailed
                },
            );
            // Expiry forbids initiating fresh native disposal. Disabled Drop preserves it.
            if Instant::now() >= deadline {
                return if collision {
                    Err(token_lock_timeout())
                } else {
                    Err(refusal.error)
                };
            }
            #[cfg(not(test))]
            let cleaned = locron_core::filesystem::remove_private_file(&candidate_path);
            #[cfg(test)]
            let cleaned = test_support::candidate_cleanup(root_path, &candidate_path, deadline);
            let timely = lock_remaining(deadline);
            if !collision {
                return Err(refusal.error);
            }
            cleaned?;
            timely?;
        }
    }
    lock_remaining(deadline)?;
    let file = locron_core::filesystem::open_private(
        &final_path,
        fs::OpenOptions::new().read(true).write(true),
    )?;
    lock_remaining(deadline)?;
    Ok(file)
}

fn token_lock_timeout() -> io::Error {
    io::Error::new(
        ErrorKind::TimedOut,
        "dashboard token is busy; retry after the current token operation finishes",
    )
}

fn valid_token(token: &str) -> bool {
    token.len() == 64 && token.bytes().all(|byte| byte.is_ascii_hexdigit())
}

fn write_atomic_0600(path: &std::path::Path, contents: &str) -> io::Result<()> {
    let root = path.parent().expect("token path always has a parent");
    let _guard = locron_core::filesystem::DirectoryGuard::private(root)?;
    let suffix = random_hex_32();
    #[cfg(test)]
    let suffix = test_support::scratch_suffix(root).unwrap_or(suffix);
    let temporary = root.join(format!(
        "{}.{}.tmp",
        path.file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("token"),
        suffix
    ));
    // A failed exclusive create does not authorize removing an existing file.
    let mut file = locron_core::filesystem::create_private_new(&temporary)?;
    #[cfg(test)]
    test_support::observe(root, test_support::Event::ScratchCreated);
    #[cfg(not(test))]
    let written = file
        .write_all(contents.as_bytes())
        .and_then(|()| file.sync_all());
    #[cfg(test)]
    let written = test_support::write_sync(root, &mut file, contents.as_bytes());
    // Release the file before cleanup/rename, including on Windows.
    drop(file);
    #[cfg(test)]
    test_support::observe(root, test_support::Event::LeafClosed);
    if let Err(error) = written {
        #[cfg(not(test))]
        let _ = locron_core::filesystem::remove_private_file(&temporary);
        #[cfg(test)]
        let _ = test_support::scratch_cleanup(root, &temporary);
        return Err(error);
    }
    #[cfg(not(test))]
    let renamed = locron_core::filesystem::rename_private(&temporary, path);
    #[cfg(test)]
    let renamed = test_support::rename(root, &temporary, path);
    if let Err(error) = renamed {
        #[cfg(not(test))]
        let _ = locron_core::filesystem::remove_private_file(&temporary);
        #[cfg(test)]
        let _ = test_support::scratch_cleanup(root, &temporary);
        return Err(error);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_paths() -> (tempfile::TempDir, StatePaths) {
        let dir = tempfile::tempdir().expect("tempdir");
        let paths = StatePaths::new(dir.path().join("private"));
        paths.ensure().expect("private test root");
        (dir, paths)
    }

    #[test]
    fn ensure_generates_then_reuses() {
        let (_dir, paths) = temp_paths();
        let first = ensure(&paths).expect("generate");
        assert!(valid_token(&first));
        let second = ensure(&paths).expect("reuse");
        assert_eq!(first, second, "an existing token must be reused");
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let metadata = fs::metadata(token_path(&paths)).expect("token file");
            assert_eq!(metadata.permissions().mode() & 0o777, 0o600);
        }
        assert!(locron_core::filesystem::is_private(&token_path(&paths), false).unwrap());
        assert_eq!(fs::read_to_string(token_path(&paths)).unwrap(), first);
    }

    #[test]
    fn regenerate_replaces_and_remove_deletes() {
        let (_dir, paths) = temp_paths();
        let first = ensure(&paths).expect("generate");
        let second = regenerate(&paths).expect("regenerate");
        assert_ne!(first, second);
        remove(&paths).expect("remove");
        assert!(fs::metadata(token_path(&paths)).is_err());
        remove(&paths).expect("second remove is a no-op");
    }

    #[test]
    fn corrupt_token_file_is_rejected() {
        let (_dir, paths) = temp_paths();
        locron_core::filesystem::create_private_new(&token_path(&paths))
            .expect("private token file")
            .write_all(b"not-a-token")
            .expect("write");
        assert_eq!(ensure(&paths).unwrap_err().kind(), ErrorKind::InvalidData);
    }
}
