//! Access-token file management.
//!
//! The dashboard access token is 32 random bytes from the OS RNG, hex-encoded to 64 characters,
//! stored owner-only (0600) at a fixed name under the state directory. It is generated on first
//! use, reused afterwards, regenerated by `enable --reset`, and removed by `disable`. The server
//! reads it at startup; a running server is unaffected by a later file change, which is why
//! `enable --reset` restarts the service. The token never appears in a URL, in logs, or in
//! responses.

use std::fs;
use std::io::{self, ErrorKind, Write};
use std::path::PathBuf;

use locron_store::StatePaths;

/// The fixed token file name under the state directory.
pub const TOKEN_FILE_NAME: &str = "dashboard.token";

/// Returns the token file path under the state directory.
#[must_use]
pub fn token_path(paths: &StatePaths) -> PathBuf {
    paths.root.join(TOKEN_FILE_NAME)
}

/// Generates 32 random bytes and hex-encodes them to a 64-character string.
///
/// Used for the access token and for per-session CSRF values.
///
/// # Panics
///
/// Panics if the OS random number generator fails.
#[must_use]
pub fn random_hex_32() -> String {
    let mut bytes = [0_u8; 32];
    getrandom::fill(&mut bytes).expect("OS random number generator must be available");
    let mut hex = String::with_capacity(64);
    for byte in bytes {
        use std::fmt::Write;
        let _ = write!(hex, "{byte:02x}");
    }
    hex
}

/// Reads the token file, generating and persisting a fresh token when the file is missing.
///
/// The state root is created (refusing a symlink at the root, mirroring the store's
/// `ensure_private_directory` posture) and the file is written atomically with 0600 permissions.
pub fn ensure(paths: &StatePaths) -> io::Result<String> {
    let path = token_path(paths);
    match fs::read_to_string(&path) {
        Ok(contents) => {
            let token = contents.trim();
            if valid_token(token) {
                Ok(token.to_owned())
            } else {
                Err(io::Error::new(
                    ErrorKind::InvalidData,
                    format!(
                        "{} does not contain a 64-character hex access token",
                        path.display()
                    ),
                ))
            }
        }
        Err(error) if error.kind() == ErrorKind::NotFound => {
            let token = random_hex_32();
            write_atomic_0600(&path, &token)?;
            Ok(token)
        }
        Err(error) => Err(error),
    }
}

/// Replaces the stored token with a fresh random one (`enable --reset` semantics).
pub fn regenerate(paths: &StatePaths) -> io::Result<String> {
    let token = random_hex_32();
    write_atomic_0600(&token_path(paths), &token)?;
    Ok(token)
}

/// Removes the token file (`disable` semantics); a missing file is not an error.
pub fn remove(paths: &StatePaths) -> io::Result<()> {
    match fs::remove_file(token_path(paths)) {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == ErrorKind::NotFound => Ok(()),
        Err(error) => Err(error),
    }
}

fn valid_token(token: &str) -> bool {
    token.len() == 64 && token.bytes().all(|byte| byte.is_ascii_hexdigit())
}

fn write_atomic_0600(path: &PathBuf, contents: &str) -> io::Result<()> {
    let root = path.parent().expect("token path always has a parent");
    match fs::symlink_metadata(root) {
        Ok(metadata) => {
            if metadata.file_type().is_symlink() || !metadata.is_dir() {
                return Err(io::Error::new(
                    ErrorKind::InvalidInput,
                    format!(
                        "state directory is not a real directory: {}",
                        root.display()
                    ),
                ));
            }
        }
        Err(error) if error.kind() == ErrorKind::NotFound => fs::create_dir_all(root)?,
        Err(error) => return Err(error),
    }
    let temporary = root.join(format!(
        "{}.tmp",
        path.file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("token")
    ));
    {
        let mut file = fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .open(&temporary)?;
        set_owner_only(&temporary)?;
        file.write_all(contents.as_bytes())?;
        file.sync_all()?;
    }
    fs::rename(&temporary, path)?;
    Ok(())
}

fn set_owner_only(path: &std::path::Path) -> io::Result<()> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(path, fs::Permissions::from_mode(0o600))
    }
    #[cfg(not(unix))]
    {
        let _ = path;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_paths() -> (tempfile::TempDir, StatePaths) {
        let dir = tempfile::tempdir().expect("tempdir");
        let paths = StatePaths::new(dir.path().to_path_buf());
        (dir, paths)
    }

    #[test]
    fn ensure_generates_then_reuses() {
        let (_dir, paths) = temp_paths();
        let first = ensure(&paths).expect("generate");
        assert!(valid_token(&first));
        let second = ensure(&paths).expect("reuse");
        assert_eq!(first, second, "an existing token must be reused");
        let metadata = fs::metadata(token_path(&paths)).expect("token file");
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            assert_eq!(metadata.permissions().mode() & 0o777, 0o600);
        }
        assert_eq!(fs::read_to_string(token_path(&paths)).unwrap(), first);
    }

    #[test]
    fn regenerate_replaces_and_remove_deletes() {
        let (_dir, paths) = temp_paths();
        let first = ensure(&paths).expect("generate");
        let second = regenerate(&paths).expect("regenerate");
        assert_ne!(first, second);
        remove(&paths).expect("remove");
        assert!(fs::metadata(token_path(&paths)).is_err());
        remove(&paths).expect("second remove is a no-op");
    }

    #[test]
    fn corrupt_token_file_is_rejected() {
        let (_dir, paths) = temp_paths();
        fs::write(token_path(&paths), "not-a-token").expect("write");
        assert!(ensure(&paths).is_err());
    }
}
