#!/usr/bin/env python3
"""Render offline bootstrap checks without loading an unverified installed script."""

from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent.parent
FUNCTIONS = (
    "Get-LocronSid", "ConvertTo-LocronPath", "Assert-LocronDescriptor",
    "Assert-LocronDirectory", "Read-LocronPrivateFile", "Get-LocronSha256",
    "ConvertFrom-LocronJson", "Assert-LocronFields", "Assert-LocronUserPath", "Read-LocronReceipt", "Get-LocronTarget",
)
HEADER = """#requires -Version 5.1
<#
Offline removal of a receipt-owned standalone installation. Uses the exact
verified retained installer bootstrap; never changes execution policy.
Generated by scripts/render-windows-uninstaller.py; shared checks come from install.ps1.
#>
[CmdletBinding()]
param([string]$InstallDirectory)

"""
FOOTER = r'''
function Invoke-LocronRemovalBootstrap {
    $selected = $InstallDirectory
    if (-not $selected) {
        $selected = if ([IO.File]::Exists([IO.Path]::Combine($PSScriptRoot, '.locron-install-receipt-v1'))) {
            $PSScriptRoot
        } else { [IO.Path]::Combine($env:LOCALAPPDATA, 'Programs', 'locron') }
    }
    $selected = ConvertTo-LocronPath $selected
    $receipt = Read-LocronReceipt $selected
    $bootstrapPath = [IO.Path]::Combine($selected, '.locron-installer.ps1')
    $bootstrap = Read-LocronPrivateFile $bootstrapPath
    if ((Get-LocronSha256 $bootstrap) -cne $receipt.files.'.locron-installer.ps1') {
        throw 'retained installer bootstrap changed; removal is refused'
    }
    # Keep the verified script immutable while its functions are loaded. Release
    # this source handle before the helper removes that owned payload; its loaded
    # functions are already in memory, and the helper repeats all live checks.
    $guard = [IO.File]::Open($bootstrapPath, [IO.FileMode]::Open, [IO.FileAccess]::Read, [IO.FileShare]::Read)
    try {
        Assert-LocronDescriptor ($guard.GetAccessControl()) $true $false
        if ($guard.Length -gt 67108864) { throw 'retained bootstrap exceeds its size limit' }
        $memory = [IO.MemoryStream]::new()
        try {
            $guard.CopyTo($memory)
            if ((Get-LocronSha256 $memory.ToArray()) -cne $receipt.files.'.locron-installer.ps1') {
                throw 'retained bootstrap changed before loading; removal is refused'
            }
        } finally { $memory.Dispose() }
        . $bootstrapPath -InstallDirectory $selected
    } finally { $guard.Dispose() }
    Invoke-LocronUninstall $selected
}

if ($MyInvocation.InvocationName -ne '.') {
    $ErrorActionPreference = 'Stop'
    $ProgressPreference = 'SilentlyContinue'
    Invoke-LocronRemovalBootstrap
}
'''


def render() -> str:
    source = (ROOT / "install.ps1").read_text(encoding="utf-8")
    functions = dict(re.findall(r"(?m)^function ([\w-]+)([^\n]*\n.*?^})", source, re.S | re.M))
    if len(functions) != source.count("\nfunction "):
        raise ValueError("unexpected installer function layout")
    return HEADER + "\n\n".join("function " + name + functions[name] for name in FUNCTIONS) + "\n" + FOOTER


if __name__ == "__main__":
    output = render()
    path = ROOT / "uninstall.ps1"
    if sys.argv[1:] == ["--check"]:
        if not path.exists() or path.read_text(encoding="utf-8") != output:
            raise SystemExit("uninstall.ps1 differs from its shared verified bootstrap source")
    elif sys.argv[1:]:
        raise SystemExit("usage: render-windows-uninstaller.py [--check]")
    else:
        path.write_text(output, encoding="utf-8", newline="\n")
